FROM agrigorev/zoomcamp-model:mlops-2024-3.10.13-slim

RUN pip install -U pip
RUN pip install pipenv pyarrow fastparquet

COPY Pipfile .
COPY Pipfile.lock .

RUN pipenv install --system --deploy

COPY starter.py .

CMD [ "python", "./starter.py", "2023", "5"]
